### ISSUE TITLE
Sporadical WebDriver timeout in acceptance tests

### ISSUE THREAD

**Issue by kj187** [spryker/docker-sdk#396]
### Which release, branch or hash of Docker SDK are you using?
master

### Which operating system (platform/version/architecture) are you using?
`ubuntu-18.04` on GitHub Actions

### What is the issue that you're experiencing?

The following error happens only **sporadically**, after a restart of the failed job it works without any issues.
In this case it was happen on Alpine, but it could also happen on Debian. Its totally sporadical.
Also the test case, in this example it is `CmsGuiCreatePageCest` but it could also be another test case.

https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3540552778/jobs/5943741993

![SCR-20221124-jtb](https://user-images.githubusercontent.com/1647861/203793492-a70349de-6b65-4095-9541-6e43959c1a7c.png)

#### What are the steps to reproduce the issue?

I forked the current Spryker Demo Shop (https://github.com/elmerdigital/b2b-demo-shop). 
The github CI which I use is the following (https://github.com/elmerdigital/b2b-demo-shop/blob/master/.github/workflows/ci.yml) 

```bash
git clone https://github.com/spryker/docker-sdk.git ./docker
docker/sdk boot -v deploy.ci.acceptance.mariadb.yml
docker/sdk up -t
docker/sdk testing console queue:worker:start --stop-when-empty
docker/sdk testing codecept run -c codeception.acceptance.yml
```

#### What is the expected result of these steps in the absence of the issue?

A successful Github job

**Comment by kj187** [comment]
Here another example from a project where we use Gitlab CI

![SCR-20221124-lu5](https://user-images.githubusercontent.com/1647861/203811147-cdaa4aae-fc35-4ce0-b636-92eb97e7162b.png)

**Comment by RozbehSharahi** [comment]
Hello,

For more convenient investigation, I want to provide some further hints here:

The issue seems to only appear on usage of `spryker/chromedriver` which uses chrome version 102. Therefore it is necessary to add it to `deploy.*.yml` for reproduction.

```
services:
    webdriver:
        engine: chromedriver
```
Reproduction is easily done by running a simple test 10 times:

```
for i in `seq 1 10`; do docker/sdk testing codecept run -g CompanyRegistrationCest; done
```
10 times in my case is already enough to always have a stuck test. 

The test will get stuck for 600secs (i think curl timeouts are not correctly set) until it will follows up with the above mentioned error message. 

**Hint:** I think an update of chrome version might solve the issue.

<3

**Comment by RozbehSharahi** [comment]
The problem seems really to be chrome version related. With following steps I tried with a new version (108).

- SET `"chromium-revision": 1084290` in composer.json
- `docker/sdk cli COMPOSER_IGNORE_CHROMEDRIVER=0 composer install`
- `docker/sdk stop && docker/sdk start && docker/sdk cli console c:c:b`

Now that chromedriver is updated, I update chrome manually in webdriver container

- `docker exec -it -uroot spryker_b2b_dev_webdriver_1 sh`
- `apk upgrade --no-cache && apk upgrade --no-cache chromium` // will currently update to 108
-  `docker/sdk stop && docker/sdk start # maybe not needed`

After that the session issue does not appear anymore:

```
for i in `seq 1 100`; do docker/sdk testing codecept run -g CompanyRegistrationCest; done
```

**Comment by alexanderM91** [comment]
Hi @RozbehSharahi, 
great and thanks a lot for your magnificent and deep investigation. 
We are planing to handle it in the nearest future.

**Comment by alexanderM91** [comment]
Hi,
Chromedriver has been updated to `1085359`.
Please pull the latest image version. 

My special gratitude for the contribution in the problem investigation.


Also, let's close an issue  and reopen it or create a new one in case of necessity. 
Thank you.
